services:
  trivy:
    image: aquasec/trivy:latest
    entrypoint: ""
    working_dir: /src
    volumes:
      - cache:/root/.cache/
      - .:/src
  binfmt:
    image: tonistiigi/binfmt
    privileged: true

volumes:
  cache:
