name: Build Container

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build the Docker image
        run: |
          make build
          make badges
          make scan

      - name: Upload results to the GitHub Security tab
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Login to Docker Hub
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make publishDockerhub

      - name: Push to GHCR
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make publishGitHub
